### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "user@user.com",
  "password": "password"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=user@user.com

### Delete a user with a given ID
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "password": "newpassword"
}